data = [
    # Documents
    ("resume.pdf", "Documents"),
    ("invoice_2024.pdf", "Documents"),
    ("cover_letter.docx", "Documents"),
    ("meeting_notes_nov.txt", "Documents"),
    ("project_proposal_v2.pdf", "Documents"),
    ("Q3_report.doc", "Documents"),
    ("contract_final.pdf", "Documents"),
    ("meeting_agenda.md", "Documents"),
    ("research_paper.rtf", "Documents"),
    ("employee_handbook.pdf", "Documents"),
    ("annual_review_2023.docx", "Documents"),
    ("newsletter_draft.txt", "Documents"),
    ("terms_of_service.rtf", "Documents"),
    ("privacy_policy.pdf", "Documents"),
    ("whitepaper_blockchain.pdf", "Documents"),
    ("product_spec_sheet.docx", "Documents"),
    ("thesis_final_draft.pdf", "Documents"),
    ("minutes_of_meeting.docx", "Documents"),
    ("billing_statement.txt", "Documents"),
    ("user_manual_english.pdf", "Documents"),
    
    # Images
    ("holiday_photo.jpg", "Images"),
    ("selfie.png", "Images"),
    ("screenshot_20231012.png", "Images"),
    ("profile_picture.jpeg", "Images"),
    ("website_mockup.svg", "Images"),
    ("logo_transparent.gif", "Images"),
    ("scanned_receipt.jpg", "Images"),
    ("company_logo.webp", "Images"),
    ("raw_camera_shot.cr2", "Images"),
    ("photoshop_project.psd", "Images"),
    ("family_portrait.jpg", "Images"),
    ("scenery_mountain.png", "Images"),
    ("infographic_marketing.png", "Images"),
    ("app_icon_flat.png", "Images"),
    ("vector_illustration.svg", "Images"),
    ("scan_document_page.tiff", "Images"),
    ("product_catalog_page1.jpg", "Images"),
    ("thumbnail_youtube.webp", "Images"),
    ("background_texture.jpg", "Images"),
    ("drawing_sketch.png", "Images"),
    
    # Videos
    ("movie.mkv", "Videos"),
    ("lecture.mp4", "Videos"),
    ("vacation_vlog.mp4", "Videos"),
    ("screen_recording_bug.avi", "Videos"),
    ("tutorial_part1.mov", "Videos"),
    ("funny_cat_video.mp4", "Videos"),
    ("gopro_footage.mp4", "Videos"),
    ("webinar_recording.webm", "Videos"),
    ("wedding_highlights.mov", "Videos"),
    ("screen_capture_demo.mp4", "Videos"),
    ("timelapse_sky.mp4", "Videos"),
    ("short_film_festival.mkv", "Videos"),
    ("animation_short.avi", "Videos"),
    ("product_promo_video.mp4", "Videos"),
    ("concert_fancam.mov", "Videos"),
    ("interview_raw_footage.mkv", "Videos"),
    ("drone_shot_beach.mp4", "Videos"),
    ("presentation_recording.webm", "Videos"),
    
    # Code
    ("project_code.py", "Code"),
    ("app.js", "Code"),
    ("index.html", "Code"),
    ("styles.css", "Code"),
    ("utils.go", "Code"),
    ("main.rs", "Code"),
    ("config.json", "Code"),
    ("Dockerfile", "Code"),
    ("utility_functions.ts", "Code"),
    ("database_schema.graphql", "Code"),
    ("deployment_script.yaml", "Code"),
    ("server.js", "Code"),
    ("script_test.sh", "Code"),
    ("Makefile", "Code"),
    ("package.json", "Code"),
    ("component_navbar.tsx", "Code"),
    ("styles_variables.scss", "Code"),
    ("main_program.cpp", "Code"),
    ("header_file.h", "Code"),
    ("script_runner.py", "Code"),
    ("index.php", "Code"),
    ("controller_user.java", "Code"),
    ("db_migration.sql", "Code"),
    
    # Audio
    ("podcast_ep1.mp3", "Audio"),
    ("interview_recording.wav", "Audio"),
    ("background_music.ogg", "Audio"),
    ("voice_memo.m4a", "Audio"),
    ("song_track_mix.mp3", "Audio"),
    ("sound_effect_laser.wav", "Audio"),
    ("audiobook_chapter1.m4b", "Audio"),
    ("guitar_solo_practice.wav", "Audio"),
    ("nature_sounds_rain.ogg", "Audio"),
    ("ringtone_chime.mp3", "Audio"),
    ("vocals_lead_raw.wav", "Audio"),
    ("synth_loop_120bpm.wav", "Audio"),
    ("dj_set_live.mp3", "Audio"),
    
    # Spreadsheets
    ("financial_model.xlsx", "Spreadsheets"),
    ("employee_list.csv", "Spreadsheets"),
    ("budget_2025.xls", "Spreadsheets"),
    ("sales_tracker_q4.csv", "Spreadsheets"),
    ("tax_calculator.xlsx", "Spreadsheets"),
    ("inventory_sheet.xlsx", "Spreadsheets"),
    ("timesheet_june.csv", "Spreadsheets"),
    ("price_list_wholesale.xlsx", "Spreadsheets"),
    ("project_timeline.xlsx", "Spreadsheets"),
    ("customer_data_export.csv", "Spreadsheets"),
    ("expense_log_2024.xlsx", "Spreadsheets"),
    ("grades_semester2.csv", "Spreadsheets"),
    
    # Presentations
    ("q1_all_hands.pptx", "Presentations"),
    ("sales_pitch.ppt", "Presentations"),
    ("investor_deck.pdf", "Presentations"),
    ("marketing_strategy.pptx", "Presentations"),
    ("keynote_presentation.key", "Presentations"),
    ("project_proposal_slides.pptx", "Presentations"),
    ("technical_architecture.pptx", "Presentations"),
    ("design_portfolio_deck.pdf", "Presentations"),
    ("training_seminar_v3.pptx", "Presentations"),
    ("annual_report_slides.ppt", "Presentations"),
    
    # Archives
    ("backup_2024.zip", "Archives"),
    ("source_code.tar.gz", "Archives"),
    ("assets.rar", "Archives"),
    ("installer_package.7z", "Archives"),
    ("documents_archive.zip", "Archives"),
    ("build_artifacts.tar", "Archives"),
    ("photos_backup_2023.zip", "Archives"),
    ("compressed_bundle.tgz", "Archives"),
    ("system_backup.iso", "Archives"),
    ("database_export.sql.gz", "Archives"),
    
    # System / Executables
    ("installer_v2.exe", "System"),
    ("update_script.bat", "System"),
    ("setup.msi", "System"),
    ("run_server.sh", "System"),
    ("driver_installer.dll", "System"),
    ("firmware_update.bin", "System"),
    ("patch_installer.exe", "System"),
    ("system_process.sys", "System"),
    ("clean_temp_files.cmd", "System"),
    ("macos_installer.dmg", "System"),
    ("debian_package.deb", "System"),
    ("redhat_package.rpm", "System"),
    
    # Databases
    ("users_dump.sql", "Database"),
    ("production_db.sqlite3", "Database"),
    ("cache_data.db", "Database"),
    ("backup_db_schema.sql", "Database"),
    ("customer_relations.mdb", "Database"),
    ("analytics_store.db", "Database"),
    ("local_storage.sqlite", "Database"),
    ("redis_backup.rdb", "Database"),
    ("postgres_dump.sql", "Database"),
    
    # Fonts
    ("Roboto-Regular.ttf", "Fonts"),
    ("OpenSans-Bold.otf", "Fonts"),
    ("FiraCode.woff2", "Fonts"),
    ("Montserrat-Light.ttf", "Fonts"),
    ("Lato-Italic.otf", "Fonts"),
    ("Arial-Font-Pack.ttf", "Fonts"),
    ("Helvetica-Medium.woff", "Fonts"),
    ("FontAwesome-Icons.ttf", "Fonts"),
    
    # E-books
    ("the_great_gatsby.epub", "E-books"),
    ("python_guide.mobi", "E-books"),
    ("comic_book.cbz", "E-books"),
    ("manga_chapter1.cbr", "E-books"),
    ("sci_fi_novel.epub", "E-books"),
    ("javascript_cookbook.pdf", "E-books"),
    ("cooking_recipes_guide.epub", "E-books"),
    ("finance_for_beginners.mobi", "E-books"),
    
    # 3D Models
    ("character_model.obj", "3D Models"),
    ("architecture_layout.stl", "3D Models"),
    ("animation_rig.fbx", "3D Models"),
    ("low_poly_car.blend", "3D Models"),
    ("furniture_3d_render.max", "3D Models"),
    ("game_asset_sword.fbx", "3D Models"),
    ("terrain_mesh.obj", "3D Models"),
    ("engine_part_cad.stl", "3D Models"),
    
    # Configs / Settings
    (".gitignore", "Config"),
    ("docker-compose.yml", "Config"),
    ("nginx.conf", "Config"),
    ("settings.ini", "Config"),
    ("application.properties", "Config"),
    ("webpack_config.js", "Config"),
    ("config_prod.yaml", "Config"),
    ("tsconfig.json", "Config"),
    ("env_template.env", "Config"),
    ("babel_config.json", "Config"),
    ("cargo.toml", "Config"),
    
    # Logs
    ("server_error.log", "Logs"),
    ("access_2024.log", "Logs"),
    ("application_trace.txt", "Logs"),
    ("system_boot.log", "Logs"),
    ("crash_dump.log", "Logs"),
    ("nginx_error_log.txt", "Logs"),
    ("database_queries.log", "Logs"),
    ("installation_log.log", "Logs"),
]